name: ON-DISPATCH-DEPLOY-STATICSITE
run-name: Deploy Static Site ( Triggered by ${{ github.event_name }} and run by ${{ github.actor }} )

on:
  repository_dispatch:
    types: [deploy-staticsite]
  workflow_dispatch:
    inputs:
      deployment-stage:
        description: 'Deployment stage (SBX, CI, STG, PROD)'
        required: true
        type: choice
        options:
          - SBX
          - CI
          - STG
          - PROD
      source-repo-owner:
        description: 'Source repository owner'
        required: true
        type: string
      source-repo-name:
        description: 'Source repository name'
        required: true
        type: string
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  
  ### TODO: May need to get build artifacts from other sources???
  get-build-artifacts-workflow-dispatch:
    name: Get build artifact
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: dr3dr3/core-pipeline/.github/workflows/staticsite-get-build-artifact.yml@main
    permissions:
      contents: none
    with:
      artifact-url: ${{ format('{0}/{1}/{2}/{3}', 'https://api.github.com/repos', inputs.source-repo-owner, inputs.source-repo-name, 'releases/latest' ) }}
      artifact-ref: ${{ format('{0}-{1}', 'RC', github.run_id ) }}

  get-build-artifacts-repo-dispatch:
    name: Get build artifact
    if: ${{ github.event.client_payload.success }}
    uses: dr3dr3/core-pipeline/.github/workflows/staticsite-get-build-artifact.yml@main
    permissions:
      contents: none
    with:
      artifact-url: ${{ format('{0}/{1}/{2}/{3}', 'https://api.github.com/repos', github.event.client_payload.source-repo-owner, github.event.client_payload.source-repo-name, 'releases/latest' ) }}
      artifact-ref: ${{ format('{0}-{1}', 'RC', github.run_id ) }}

  environment-logic:
    name: Get target environment for deployment
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: none
    outputs:
      target: ${{ steps.target.outputs.TARGET }}
    env:
      DEPLOYMENT_STAGE: ${{ github.event.client_payload.deployment-stage || inputs.deployment-stage }}
    ### TODO: Read config from environment/staticsite.yml
    ### TODO: Get env variables from service repo where need (as outputs for deploy step). Secrets?
    ### TODO: Check infrastructure is ready (i.e. Vercel project exists)
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Target
        id: target
        run: |
          config=$(ds=$DEPLOYMENT_STAGE yq '.environments[] | select(.id == env(ds))' configuration/environments/staticsite.yml -o=json | jq -c)
          target=$(echo $config | jq -r '.target')
          echo $target
          echo "TARGET=$target" >> $GITHUB_OUTPUT

  ### New job... IF infrastructure is not ready, then do day1 creation of infrastructure

  ### New job... check if required secrets exist (i.e. VERCEL_ORG_ID)

  #===== VERCEL =========================================================================================#

  vercel-variables:
    name: Set Vercel environment variables
    needs: [get-build-artifacts-workflow-dispatch, get-build-artifacts-repo-dispatch, environment-logic]
    if: ${{ needs.environment-logic.outputs.target == 'VERCEL' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: none
    outputs:
      vercel-project-id: ${{ steps.vercel-project-id.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Node dependencies
        run: npm install

      - name: Get variables from repository
        id: vercel-project-id
        run: .github/actions-scripts/repo-vars-get-value.mjs
        env:
          GHA_TOKEN: ${{ secrets.GHAPAT_IDP_REPO }}
          REPO_OWNER: ${{ inputs.source-repo-owner }}
          REPO_NAME: ${{ inputs.source-repo-name }}
          VAR_NAME: 'VERCEL_PROJECT_ID'

  deploy-vercel:
    name: Deploy to ${{ github.event.client_payload.deployment-stage }} environment
    needs: [vercel-variables, environment-logic]
    ### if: ${{ needs.environment-logic.outputs.target == 'VERCEL' }}
    uses: dr3dr3/core-ops/.github/workflows/staticsite-vercel-deployment.yml@main
    permissions:
      contents: none
    secrets: inherit
    with:
      artefact-ref: ${{ format('{0}-{1}', 'RC', github.run_id ) }}
      vercel-project-id: ${{ needs.vercel-variables.outputs.vercel-project-id }}